### ISSUE TITLE
Create Automated Build on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [benschweizer/iops#16]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags automatically from git tags & branches.
Also, documentation could include an example ```docker run``` command which would become the canonical, no-install-needed way to run latest iops.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags. Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays ABs when listing images (mine is also listed):
```
$ docker search iops
NAME                          DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
pataquets/iops                iops                                            0                    [OK]
[...]
```
After #15 is in, just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by pataquets** [comment]
@cxcv : Bump (in case you didn't get any notification)

**Comment by pataquets** [comment]
@benschweizer: Bump (in case you didn't get any notification)

**Comment by pataquets** [comment]
@benschweizer ping

**Comment by benschweizer** [comment]
Hi @pataquets 

here it is:
https://hub.docker.com/repository/docker/cxcv/iops

Could you provide an example how to get a blockdev inside the container?


Cheers
Benjamin

**Comment by pataquets** [comment]
Awesome, @benschweizer !
I guess you're looking for docker run's [--device](https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device) option. Let me know if you find any problem.
Unfortunately, I'm away from any PC, and I can't tell when I will be able to try it, but I'll let you know.

**Comment by pataquets** [comment]
Usage example provided via 0afc5d35287adeb6f25d9385e40af29b41e9efce.
Closing as completed.
