### ISSUE TITLE
ZFS?

### ISSUE THREAD

**Issue by claytondukes** [benschweizer/iops#17]
Is it possible to test a ZFS mount with this?

ZFS mounts don't show in `df` as traditional devices, e.g.:

```
root@logz01 [~]: # df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   50G  7.1G   43G  15% /
/dev/mapper/centos-home  876G  856M  875G   1% /home
zpool                  41T   96K   41T   1% /zfs
```

**Comment by benschweizer** [comment]
Hi @claytondukes,

you could
i) benchmark the underlying raw devices
ii) benchmark some very big file on top of zfs

I'm not familiar if you can have a blockdevice out of zfs.

Cheers
