### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by a1exsh** [benschweizer/iops#6]
Do you want a patch for python3 compat?

Thanks.
Alex

**Comment by benschweizer** [comment]
Hi Alex,

sure, I would do python3 if i would start over today. So if you want to do
the work, feel free.

Greetings
Benjamin

**Comment by scottchiefbaker** [comment]
It's 2021 now... and Python 2 on modern distros can be problematic. Any updates on a Python 3 version?
