### ISSUE TITLE
Exception on FreeBSD with device blocksize >512

### ISSUE THREAD

**Issue by rostwald** [benschweizer/iops#7]
Hello,

I was trying to trace down a performance issue with FC-targets on FreeBSD10.3 when i stumbled over an issue with iops. If the devices report a blocksize of 512byte, iops is working as expected, however, if the blocksize is set to anything bigger (1024, 2048...), iops is failing with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./iops", line 258, in results_wrap
    result = func(*__args, **__kw)
  File "./iops", line 205, in iops
    blockdata = fh.read(blocksize)
IOError: [Errno 22] Invalid argument
```

I'm happy to help with further information or testing.

Thanks,
Sebastian

**Comment by benschweizer** [comment]
That's strange, please use tracebackturbo to dump all variables, https://github.com/cxcv/python-tracebackturbo
Is this at the first read or randomly when we hit some boundary?
I need to find a freebsd box for testing, but I am on a trip right now with limited time, I'll look into this on the weekend

**Comment by benschweizer** [comment]
Hi,

there's an updated version in github, please give it a try.

Greetings
Benjamin

http://benjamin-schweizer.de/contact
Am 28.03.2016 6:27 nachm. schrieb "rostwald" notifications@github.com:
